### ISSUE TITLE
sass/ejsコンパイルとブラウザリロード　タイミングが逆

### ISSUE THREAD

**Issue by IYA-UFO** [psephopaiktes/ejs-test#1]
## 事象
gulp-server時にsassやejsを編集・保存した時、リロードが先に起こるのでブラウザに結果が反映されません。もう一回リロードすると反映されます。

## 備考（参考までに）
できればですが、CSSの変更反映はリロードではなくインジェクションだと有難いです。個人的には細かい調整がすごく快適になりました。
https://blog.mismithportfolio.com/web/20160927browsersyncstream

何らかの直列化が必要かも
https://qiita.com/naokitomita/items/d18135b69d917b0d08e4

**Comment by psephopaiktes** [comment]
@IYA-UFO 
SCSSの変換が時間がかかるので、リロードに間に合わなかったようですね。
SCSSからPostCSSに変換することでとりあえず解決したようです。
今後フォルダが増えて再発するようであればrun-sequenceの導入を検討します。

> できればですが、CSSの変更反映はリロードではなくインジェクションだと有難いです。個人的には細かい調整がすごく快適になりました。

対応しました
